name: Android APK (Expo)

on:
  workflow_dispatch:
  push:
    branches: [ recover-my-app, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_NO_TELEMETRY: 1
      CI: '1'  # expo non-interactive
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install JS deps + Expo Versionsabgleich
        shell: bash
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: 'true'
        run: |
          set -e
          npm config set fund false
          npm config set audit false
          npm install --no-optional || npm install --force
          npx --yes expo --version || true
          npx --yes expo install --fix
          npx --yes expo install react react-native

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Expo prebuild (Android)
        shell: bash
        run: npx --yes expo prebuild --platform android --clean

      - name: Build Debug APK via Gradle Wrapper
        working-directory: android
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: android/app/build/outputs/apk/debug/*.apk
