name: Android Debug APK
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      _JAVA_OPTIONS: "-Xmx3g -XX:+UseParallelGC"
      GRADLE_OPTS: "-Xmx3g -Dorg.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.heap.size=1024m"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: |
          npm i --legacy-peer-deps

        - name: Set up JDK 17

          uses: actions/setup-java@v4

          with:

            distribution: temurin

            java-version: "17"
      - name: Set up Android SDK (API 34)
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          components: build-tools;34.0.0

      - name: Expo prebuild (create android)
        run: |
          npx expo --version || npm i -D expo
          npx expo prebuild --platform android --no-install

      - name: Build Debug (installierbar)
        run: |
          cd android
          chmod +x ./gradlew || true
          ./gradlew --no-daemon assembleDebug -x lint -x test

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: android/app/build/outputs/apk/debug/*.apk
