name: Android APK (RN/Expo)
on:
  workflow_dispatch:
  push:
    branches:
      - recover-my-app
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node für React Native / Expo
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install JS dependencies (robust)
        shell: bash
        run: |
          set -e
          if [ -f yarn.lock ]; then
            corepack enable
            yarn --version || true
            yarn install --immutable || yarn install
          else
            # npm stabilisieren
            npm config set fund false
            npm config set audit false
            if [ -f package-lock.json ]; then
              npm ci || npm install --legacy-peer-deps || npm install --force
            else
              npm install --legacy-peer-deps || npm install --force
            fi
          fi

      # JDK + Gradle
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle 8.3
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.3

      - name: Build Debug APK (android/)
        run: gradle -p android --no-daemon --stacktrace assembleDebug

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: android/app/build/outputs/apk/debug/*.apk
