name: Android Release (APK)
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      _JAVA_OPTIONS: "-Xmx3g -XX:+UseParallelGC"
      GRADLE_OPTS: "-Xmx3g -Dorg.gradle.jvmargs='-Xmx3g -Dkotlin.daemon.heap.size=1024m'"
    steps:
      - uses: actions/checkout@v4
      - name: Print baseline
        run: |
          node -v || true
          npm -v || true
          java -version || true
          uname -a
      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - name: Install Android SDK cmdline-tools (fix)
        run: |
          set -eux
          ANDROID_HOME="$HOME/android-sdk"
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          curl -sL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o /tmp/cmdtools.zip
          unzip -q /tmp/cmdtools.zip -d "$ANDROID_HOME"
          mkdir -p "$ANDROID_HOME/cmdline-tools/latest"
          mv "$ANDROID_HOME/cmdline-tools/cmdline-tools/"* "$ANDROID_HOME/cmdline-tools/latest/" || true
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses >/dev/null
          "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" "platform-tools" "build-tools;34.0.0" "platforms;android-34" >/dev/null
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci --legacy-peer-deps; else npm i --legacy-peer-deps; fi
      - name: Expo prebuild
        run: |
          npx expo --version || npm i -D expo
          if [ ! -d android ]; then npx expo prebuild --platform android --no-install; else npx expo prebuild --platform android --no-install --clean || true; fi
          ls -la android || true
      - name: Gradle assembleRelease
        run: |
          cd android
          chmod +x ./gradlew || true
          ./gradlew --no-daemon assembleRelease -x lint -x test
      - uses: actions/upload-artifact@v4
        with: { name: apk, path: android/app/build/outputs/apk/release/*.apk }
