name: Android Debug APK
on: { push: {}, workflow_dispatch: {} }

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      _JAVA_OPTIONS: "-Xmx3g -XX:+UseParallelGC"
      GRADLE_OPTS: "-Xmx3g -Dorg.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.heap.size=1024m"
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }

      - name: Set up Android SDK (API 34)
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          components: platform-tools

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install JS deps (robust)
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack enable || true
            corepack prepare pnpm@8 --activate || npm i -g pnpm
            pnpm install --no-frozen-lockfile
          elif [ -f yarn.lock ]; then
            corepack enable || true
            corepack prepare yarn@4 --activate || true
            (yarn install --no-immutable || yarn install)
          elif [ -f package-lock.json ]; then
            (npm ci --legacy-peer-deps || npm i --legacy-peer-deps)
          else
            npm i --legacy-peer-deps
          fi

      - name: Check android tree
        run: |
          ls -la android || exit 1
          ls -la android/gradlew || exit 1
          sed -n '1,200p' android/settings.gradle || true

      - name: Gradle tasks (liste)
        working-directory: android
        run: |
          chmod +x ./gradlew || true
          ./gradlew tasks --all --no-daemon --warning-mode all | tee ../gradle-tasks.txt || true

      - name: Build APK (debug)
        working-directory: android
        run: |
          chmod +x ./gradlew || true
          ./gradlew --version || true
          ./gradlew clean --no-daemon || true
          ./gradlew assembleDebug -x lint --stacktrace --no-daemon --warning-mode all | tee ../gradle-build.log \
            || ./gradlew :app:assembleDebug -x lint --stacktrace --no-daemon --warning-mode all | tee -a ../gradle-build.log
          echo "Outputs:"; find app/build/outputs -type f -maxdepth 4 -print || true
          cp -r app/build/outputs ../_outputs 2>/dev/null || true

      - name: Upload Gradle info/log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-info
          path: |
            gradle-tasks.txt
            gradle-build.log
          if-no-files-found: ignore

      - name: Upload outputs (all)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            _outputs/**
            android/**/outputs/**
          if-no-files-found: warn

      - name: Upload APKs (any module/variant)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: |
            android/app/build/outputs/**/*.apk
            android/**/outputs/**/*.apk
          if-no-files-found: warn
