name: Android Debug APK
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      _JAVA_OPTIONS: "-Xmx3g -XX:+UseParallelGC"
      GRADLE_OPTS: "-Xmx3g -Dorg.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.heap.size=1024m"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK (API 34)
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          components: platform-tools

      - name: Clean npm cache (safety)
        run: |
          npm cache clean --force || true

      - name: Install deps
        run: |
          npm ci --legacy-peer-deps

      # Nur wenn KEIN android/-Ordner im Repo liegt:
      - name: Expo prebuild (create android)
        if: ${{ !hashFiles('android/**') }}
        env:
          EXPO_NO_TELEMETRY: "1"
          EXPO_DEBUG: "1"
        run: |
          npx expo --version || npm i -D expo@53
          npx expo install --fix || true
          npx expo prebuild --platform android --no-install --clean
          ls -la android || true

      - name: Build APK (debug)
        working-directory: android
        run: |
          chmod +x ./gradlew || true
          ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
