name: Android Release (APK)
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK cmdline-tools
        run: |
          ANDROID_HOME="$HOME/android-sdk"
          mkdir -p "$ANDROID_HOME/cmdline-tools/latest"
          curl -sL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdtools.zip
          unzip -q cmdtools.zip -d "$ANDROID_HOME/cmdline-tools/latest"
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses >/dev/null
          "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" "platform-tools" "build-tools;34.0.0" "platforms;android-34" >/dev/null
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm i --legacy-peer-deps

      - name: Expo prebuild (falls nötig)
        run: |
          if [ -f app.json ] || [ -f app.config.js ]; then
            npx expo --version || npm i -D expo
            npx expo prebuild --platform android --no-install || true
          fi

      # === Signing optional: Repo-Secrets setzen, dann wird Release signiert ===
      - name: Configure signing (optional)
        if: ${{ secrets.ANDROID_KEYSTORE_B64 != '' }}
        run: |
          cd android
          echo "$ANDROID_KEYSTORE_B64" | base64 -d > app/release.keystore
          cat >> gradle.properties <<'PROPS'
ANDROID_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}
ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}
ANDROID_KEYSTORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
PROPS
          sed -i 's/android {/&\
    signingConfigs {\
        release {\
            storeFile file("app\/release.keystore")\
            storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD") ?: project.properties["ANDROID_KEYSTORE_PASSWORD"]\
            keyAlias System.getenv("ANDROID_KEY_ALIAS") ?: project.properties["ANDROID_KEY_ALIAS"]\
            keyPassword System.getenv("ANDROID_KEY_PASSWORD") ?: project.properties["ANDROID_KEY_PASSWORD"]\
        }\
    }\
    buildTypes {\
        release {\
            signingConfig signingConfigs.release\
        }\
    }/' app/build.gradle || true

      - name: Gradle assembleRelease
        run: |
          cd android
          chmod +x ./gradlew || true
          ./gradlew --no-daemon assembleRelease -x lint -x test

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: android/app/build/outputs/apk/release/*.apk
