name: Android Debug APK
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      _JAVA_OPTIONS: "-Xmx3g -XX:+UseParallelGC"
      GRADLE_OPTS: "-Xmx3g -Dorg.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.heap.size=1024m"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps

        run: |

          npm ci --legacy-peer-deps

      - name: Set up Android SDK (API 34)
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          components: build-tools;34.0.0

      - name: Expo prebuild (create android)

        env:

          EXPO_NO_TELEMETRY: "1"

          EXPO_DEBUG: "1"

        run: |

          npx expo --version || npm i -D expo@53

          npx expo install --fix || true

          npx expo prebuild --platform android --no-install --clean --non-interactive

          ls -la android || true
          name: apk-debug
          path: android/app/build/outputs/apk/debug/*.apk
