name: Android APK
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Installiere Gradle 8.3 ohne Wrapper
      - name: Setup Gradle 8.3
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.3

      - name: Gradle Version
        run: gradle --version

      - name: Cache Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build Debug APK
        run: gradle --no-daemon --stacktrace assembleDebug

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: android/app/build/outputs/apk/debug/*.apk
