name: APK Build Manual
on:
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create GitHub Release with (unsigned) APK"
        required: false
        default: "false"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: gradle/actions/setup-gradle@v3
      - uses: android-actions/setup-android@v3

      - name: Ensure gradlew executable
        run: |
          if [ -f android/gradlew ]; then chmod +x android/gradlew; fi

      - name: Build (assembleRelease)
        working-directory: android
        run: ./gradlew --console=plain --no-daemon :app:assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/*.apk
          if-no-files-found: error

  release:
    needs: build
    if: ${{ github.event.inputs.create_release == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-release
          path: .
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: "*.apk"
