name: APK Build Manual v3
on:
  workflow_dispatch:
    inputs:
      create_release:
        description: Create GitHub release (true/false)
        required: false
        default: 'true'
  repository_dispatch:
    types: [manual_apk_build]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: gradle/actions/setup-gradle@v3
      - uses: android-actions/setup-android@v3

      - name: Debug: event & secrets presence
        env:
          EVENT_NAME: ${{ github.event_name }}
          HAS_B64: ${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 != '' }}
          HAS_STORE_PASS: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD != '' }}
          HAS_ALIAS: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS != '' }}
          HAS_KEY_PASS: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD != '' }}
        run: |
          echo "event=$EVENT_NAME"
          echo "has_keystore_b64=$HAS_B64"
          echo "has_store_password=$HAS_STORE_PASS"
          echo "has_key_alias=$HAS_ALIAS"
          echo "has_key_password=$HAS_KEY_PASS"

      - name: Restore keystore from secret (robust)
        if: ${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 != '' }}
        shell: bash
        run: |
          set -euo pipefail
          # Versuch 1: printf | base64 -d (Secret ist 1 Zeile, -A encodiert)
          if printf '%s' '${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 }}' | base64 -d > "$HOME/release.jks" 2>/dev/null; then
            :
          else
            echo "base64 -d via printf fehlgeschlagen – Fallback openssl …"
            # Versuch 2: openssl base64 -d -A
            python3 - <<'PY' > "$HOME/release.jks"
import base64, sys
s = """${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 }}""".strip().encode()
sys.stdout.buffer.write(base64.b64decode(s))
PY
          fi
          install -m 600 "$HOME/release.jks" "$HOME/release.jks"
          ls -l "$HOME/release.jks" || true
          file "$HOME/release.jks" || true

      - name: Export signing env
        if: ${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 != '' }}
        shell: bash
        run: |
          {
            echo "ANDROID_SIGNING_STORE_FILE=$HOME/release.jks";
            echo "ANDROID_SIGNING_STORE_PASSWORD=${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}";
            echo "ANDROID_SIGNING_KEY_ALIAS=${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}";
            echo "ANDROID_SIGNING_KEY_PASSWORD=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}";
          } >> "$GITHUB_ENV"
          echo "Exported signing env vars."

      - name: Ensure gradlew executable
        run: |
          if [ -f android/gradlew ]; then chmod +x android/gradlew; fi

      - name: Build (assembleRelease)
        working-directory: android
        run: ./gradlew --console=plain --no-daemon :app:assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
