name: apk-build

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: "GitHub Release erstellen und APK anhängen?"
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: gradle/actions/setup-gradle@v3

      - uses: android-actions/setup-android@v3

      # Node + JS-Deps (für React Native/Expo)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            **/package-lock.json
            yarn.lock
            **/yarn.lock
            pnpm-lock.yaml
            **/pnpm-lock.yaml

      - name: Install JS dependencies
        run: |
          if [ -f package.json ]; then
            set -e
            corepack enable || true
            if [ -f yarn.lock ]; then
              corepack prepare yarn@stable --activate || true
              yarn install --frozen-lockfile
            elif [ -f pnpm-lock.yaml ]; then
              corepack prepare pnpm@latest --activate || true
              pnpm install --frozen-lockfile
            elif [ -f package-lock.json ]; then
              npm ci
            else
              npm i
            fi
          else
            echo "Keine package.json im Repo – überspringe JS-Deps."
          fi

      - name: Restore keystore from secret
        if: ${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 !=  }}
        run: echo "$ANDROID_SIGNING_KEYSTORE_BASE64" | base64 -d > "$HOME/release.jks"
        env:
          ANDROID_SIGNING_KEYSTORE_BASE64: ${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 }}

      - name: Configure Gradle signing (if keystore present)
        run: |
          if [ -f "$HOME/release.jks" ]; then
            mkdir -p ~/.gradle
            cat > ~/.gradle/gradle.properties <<EOF
            MY_SIGNING_STORE_FILE=${HOME}/release.jks
            MY_SIGNING_STORE_PASSWORD=${{ secrets.ANDROID_SIGNING_KEYSTORE_PASSWORD }}
            MY_SIGNING_KEY_ALIAS=${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
            MY_SIGNING_KEY_PASSWORD=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
            EOF
          else
            echo "No keystore provided – baue unsigned APK."
          fi

      - name: Build (assembleRelease)
        run: |
          set -e
          LOGDIR="$PWD/build-logs"; mkdir -p "$LOGDIR"
          if [ -x ./gradlew ]; then
            chmod +x ./gradlew
            ./gradlew --no-daemon assembleRelease --stacktrace --console=plain 2>&1 | tee "$LOGDIR/gradle-build.log"
          elif [ -x ./android/gradlew ]; then
            chmod +x ./android/gradlew
            (cd android && ./gradlew --no-daemon assembleRelease --stacktrace --console=plain) 2>&1 | tee "$LOGDIR/gradle-build.log"
          else
            echo "Gradle wrapper nicht gefunden"; exit 1
          fi

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: build-logs/*.log
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload artifact (android-apk)
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            **/build/outputs/apk/release/*.apk
          if-no-files-found: error
          retention-days: 7

      - name: Create GitHub Release and upload APK(s)
        if: ${{ inputs.create_release == true }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Build ${{ github.run_number }}"
          draft: false
          prerelease: false
          files: |
            **/build/outputs/apk/release/*.apk
