name: apk-build

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: "GitHub Release erstellen und APK anhängen?"
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # ---- Keystore aus Secrets wiederherstellen ----
      - name: Restore keystore from secret
        run: |
          echo "$ANDROID_SIGNING_KEYSTORE_BASE64" | base64 -d > "$HOME/release.jks"
        shell: bash
        env:
          ANDROID_SIGNING_KEYSTORE_BASE64: ${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 }}

      - name: Configure Gradle signing
        run: |
          mkdir -p ~/.gradle
          cat > ~/.gradle/gradle.properties <<EOF
          MY_SIGNING_STORE_FILE=${HOME}/release.jks
          MY_SIGNING_STORE_PASSWORD=${{ secrets.ANDROID_SIGNING_KEYSTORE_PASSWORD }}
          MY_SIGNING_KEY_ALIAS=${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          MY_SIGNING_KEY_PASSWORD=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          EOF
        shell: bash

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build (assembleRelease)
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload artifact (android-apk)
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            android/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
          retention-days: 7

      # ---- Optional: Release erstellen + APK anhängen ----
      - name: Create GitHub Release and upload APK(s)
        if: ${{ inputs.create_release == true }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Build ${{ github.run_number }}"
          draft: false
          prerelease: false
          files: |
            android/app/build/outputs/apk/release/*.apk
