name: EAS Build
on:
  workflow_dispatch:
    inputs:
      easProfile:
        description: "EAS profile"
        required: true
        default: "production"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Install EAS CLI (global, npm-only)
        run: npm i -g eas-cli@16

      - name: Verify EAS auth
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas whoami

      - name: EAS Cloud build (wait & download)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          CI: "true"
        run: |
          set -e
          # Cloud build, warte bis fertig, schreibe Summary JSON
          eas build -p android --profile ${{ github.event.inputs.easProfile }} --non-interactive --wait --json > build.json
          # Neueste Android-APK ziehen
          eas build:download --latest --platform android -o app-release.apk
          ls -lh app-release.apk || (echo "APK fehlt" && exit 1)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            app-release.apk
            build.json
