name: EAS Build (register)
on:
  workflow_dispatch:
    inputs:
      easProfile:
        description: "EAS profile"
        required: true
        default: "production"
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "workflow_dispatch OK"
