name: EAS Build Dispatch
on:
  workflow_dispatch:
    inputs:
      easProfile:
        description: EAS profile
        required: true
        default: production

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Install EAS CLI
        run: npm i -g eas-cli@16
      - name: EAS build (android)
        env:
          EAS_PROFILE: ${{ github.event.inputs.easProfile }}
        run: bash ci/eas_build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: build-metadata
          path: build.json
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app-release.apk
          if-no-files-found: ignore
