name: EAS Build Dispatch

on:
  workflow_dispatch:
    inputs:
      easProfile:
        description: "EAS profile"
        required: true
        default: "production"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "DISPATCH OK - ${{ github.event.inputs.easProfile }}"
