name: EAS Build
on:
  workflow_dispatch:
    inputs:
      easProfile:
        description: "EAS profile"
        required: true
        default: "production"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Deps nur per npm (klein halten)
      - name: Install deps
        run: npm ci --no-audit --no-fund

      # EAS CLI global (npm-only)
      - name: Install EAS CLI (global)
        run: npm i -g eas-cli@16

      # Optionaler Gesundheitscheck (ignoriert Fehler)
      - name: expo doctor (optional)
        run: npx expo-doctor || true
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # EAS Cloud Build (Android APK/AAB je nach eas.json)
      - name: EAS Build (cloud)
        run: |
          eas --version
          eas whoami
          eas build -p android --profile "${{ github.event.inputs.easProfile }}" --non-interactive --json > build.json
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Metadata hochladen (damit man build.json sieht)
      - uses: actions/upload-artifact@v4
        with:
          name: build-metadata
          path: build.json
