name: EAS Build
on:
  workflow_dispatch:
    inputs:
      easProfile:
        description: "EAS profile"
        required: true
        default: "production"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20", cache: "npm" }
      - name: Install deps (npm only)
        run: npm ci --no-audit --no-fund
      - name: Install EAS CLI (nodal)
        run: npm i -g eas-cli@16
      - name: Verify EAS & linken projekt
        env: { EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} }
        run: |
          set -e
          eas --version
          eas whoami
          eas project:info || eas project:init --non-interactive --force || true
      - name: expo doctor (optional)
        env: { EXPO_TOKEN: ${+{ secrets.EXPO_TOKEN }} }
        run: npx expo-doctor || true
      - name: EAS Cloud build (Android)
        env: { EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} }
        run: |
          eas build -p android --profile "${{ github.event.inputs.easProfile }}" --non-interactive --json > build.json
          cat build.json
      - uses: actions/upload-artifact@v4
        with: { name: build-metadata, path: build.json }
