name: EAS Build
on:
  workflow_dispatch:
    inputs:
      easProfile:
        description: "EAS profile"
        required: true
        default: "production"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Ensure minimal configs (no commit, just for CI)
        run: |
          set -euo pipefail
          if [ ! -f app.json ] && [ ! -f app.config.js ]; then
            cat > app.json <<'JSON'
{
  "expo": {
    "name": "K1W1 Builder",
    "slug": "k1w1-builder",
    "android": { "package": "com.k1w1.builder" }
  }
}
JSON
          fi
          if [ ! -f eas.json ]; then
            cat > eas.json <<'JSON'
{
  "build": {
    "production": {
      "android": { "buildType": "apk" }
    }
  }
}
JSON
          fi

      - name: Install deps (npm)
        run: npm ci --no-audit --no-fund

      - name: Install EAS CLI (global, no yarn)
        run: npm i -g eas-cli@16

      - name: Ensure Docker is up
        run: |
          sudo systemctl start docker 2>/dev/null || sudo service docker start 2>/dev/null || true
          docker info >/dev/null

      - name: Local Android build (APK) with EAS (no Expo account)
        env:
          EAS_NO_VCS: "1"
          CI: "true"
        run: |
          set -e
          eas --version
          eas build --local -p android --profile ${{ github.event.inputs.easProfile }} \
            --non-interactive --output app-release.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app-release.apk
