name: Manual APK Build Final
on:
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create GitHub release (true/false)"
        required: false
        default: 'true'
  repository_dispatch:
    types: [manual_apk_build]
  push:
    branches: [main]
    paths:
      - ".github/force-run-apk"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: gradle/actions/setup-gradle@v3
      - uses: android-actions/setup-android@v3

      - name: Debug: event & secrets presence
        shell: bash
        run: |
          echo "event=${{ github.event_name }}"
          echo "has_keystore_b64=$([ -n "${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 }}" ] && echo true || echo false)"
          echo "has_store_password=$([ -n "${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}" ] && echo true || echo false)"
          echo "has_key_alias=$([ -n "${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}" ] && echo true || echo false)"
          echo "has_key_password=$([ -n "${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}" ] && echo true || echo false)"

      - name: Restore keystore from secret (robust)
        if: ${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 != '' }}
        shell: bash
        run: |
          set -euo pipefail
          base64 -d > "$HOME/release.jks" <<< '${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 }}'
          install -m 600 "$HOME/release.jks" "$HOME/release.jks"
          ls -l "$HOME/release.jks" || true
          file "$HOME/release.jks" || true

      - name: Export signing env
        if: ${{ secrets.ANDROID_SIGNING_KEYSTORE_BASE64 != '' }}
        shell: bash
        run: |
          {
            echo "ANDROID_SIGNING_STORE_FILE=$HOME/release.jks";
            echo "ANDROID_SIGNING_STORE_PASSWORD=${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}";
            echo "ANDROID_SIGNING_KEY_ALIAS=${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}";
            echo "ANDROID_SIGNING_KEY_PASSWORD=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}";
          } >> "$GITHUB_ENV"
          echo "Exported signing env vars."

      - name: Ensure gradlew executable
        run: |
          if [ -f android/gradlew ]; then chmod +x android/gradlew; fi

      - name: Build (assembleRelease)
        working-directory: android
        run: ./gradlew --console=plain --no-daemon :app:assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
