name: Manual APK Build (v10 bulletproof)
on:
  push:
    paths: [".github/force-run-apk-v10"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Android SDK (CLI)
        run: |
          set -euxo pipefail
          ANDROID_SDK_ROOT="$HOME/android-sdk"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o clt.zip
          unzip -q clt.zip && rm clt.zip
          mv cmdline-tools latest
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-34" "build-tools;34.0.0" || true
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses || true
          {
            echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          } >> "$GITHUB_ENV"
          echo "$ANDROID_SDK_ROOT/platform-tools"     >> "$GITHUB_PATH"
          echo "$ANDROID_SDK_ROOT/build-tools/34.0.0" >> "$GITHUB_PATH"

      - name: (Optional) Setup Node (nur wenn JS vorhanden)
        uses: actions/setup-node@v4
        if: ${{ hashFiles('**/package.json') != '' || hashFiles('**/yarn.lock') != '' }}
        with:
          node-version: '20'
          cache: 'npm'

      - name: (Optional) JS-Deps installieren
        if: ${{ hashFiles('**/package.json') != '' || hashFiles('**/yarn.lock') != '' }}
        run: |
          set -euxo pipefail
          if [ -f yarn.lock ]; then
            corepack enable || true
            yarn install --immutable || yarn install --frozen-lockfile || yarn install --ignore-engines
          else
            npm ci --no-audit --no-fund --legacy-peer-deps || npm install --no-audit --no-fund --legacy-peer-deps
          fi

      - name: Gradle Wrapper finden
        id: gw
        run: |
          set -euo pipefail
          f="$(git ls-files | grep -E '(^|/)gradlew$' | head -n1 || true)"
          if [ -z "${f:-}" ]; then
            echo "❌ No gradlew found"; exit 1
          fi
          echo "gradlew=$f" >> "$GITHUB_OUTPUT"
          echo "dir=$(dirname "$f")" >> "$GITHUB_OUTPUT"

      - name: Release bauen (mit Fallback)
        working-directory: ${{ steps.gw.outputs.dir }}
        run: |
          set -euo pipefail
          chmod +x ./gradlew || true
          ./gradlew --console=plain --no-daemon assembleRelease || ./gradlew --console=plain --no-daemon :app:assembleRelease

      - name: Release-Artefakte einsammeln (garantiert)
        run: |
          set -euxo pipefail
          mkdir -p release-apks
          # APK/AAB einsammeln und auf fixe Namen mappen
          APK="$(find . -type f -path "*/outputs/apk/release/*.apk" | head -n1 || true)"
          AAB="$(find . -type f -path "*/outputs/bundle/release/*.aab" | head -n1 || true)"
          [ -n "${APK:-}" ] && cp "$APK" release-apks/app-release.apk || true
          [ -n "${AAB:-}" ] && cp "$AAB" release-apks/app-release.aab || true
          # Falls gar nichts gefunden wurde → Dummy, damit immer ein Artifact existiert
          if [ -z "${APK:-}" ] && [ -z "${AAB:-}" ]; then
            echo "No APK/AAB built" > release-apks/NO_BUILD.txt
          fi
          ls -lhR release-apks || true

      - name: Artifact hochladen (immer)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: release-apks/*
          if-no-files-found: warn
